name: EILEEN
favicon: null
layout_spectrum: 0.06586757092736661
typography_spectrum: 0.577906038146466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9141316288150847
  lightness: 0.9404859384521842
  saturation: 0.5630207483191043
  rhythmicContrast: 0.3047426564153284
purpose: []
