name: EILEEN
favicon: null
layout_spectrum: 0.95718
typography_spectrum: 0.577906038146466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#348fac'
    - '#bcbcbc'
    - '#4f4f4f'
    - '#262626'
  brandStrength: 0.4375
  lightness: 0.9404859384521842
  saturation: 0.5630207483191043
  rhythmicContrast: 0.3047426564153284
purpose: []
